name: soundpool
description: A Flutter Sound Pool for playing short audio files. Sound tracks are cached in memory and played directly from cache.
version: 0.5.4
author: Lukasz Huculak <ukasz.apps@gmail.com>
homepage: https://github.com/ukasz123/soundpool

environment:
  sdk: ">=2.0.0-dev.48.0 <3.0.0"
  flutter: ">=0.4.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter


flutter:
  plugin:
    androidPackage: pl.ukaszapps.soundpool
    pluginClass: SoundpoolPlugin

