name: soundpool_macos
description: A Flutter Sound Pool for playing short audio files. Sound tracks are cached in memory and played directly from cache.
version: 0.2.7
homepage: https://github.com/ukasz123/soundpool/tree/master/soundpool_macos


environment:
  sdk: '>=2.12.0 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  soundpool_platform_interface: 
      path : ../soundpool_platform_interface


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: SwiftSoundpoolPlugin
